CREATE TABLE tsq.`yields` (
  `id` BIGINT UNSIGNED NOT NULL COMMENT 'PK, FK to prices.id',
  `update_time` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '',
  `clearance_profit` DECIMAL(16,10) DEFAULT NULL COMMENT 'Доходность к погашения простая (от индик. цены), в долях',
  `offer_profit` DECIMAL(16,10) DEFAULT NULL COMMENT 'Доходность к оферте простая (от индик. цены), в долях',
  `clearance_profit_effect` DECIMAL(16,10) DEFAULT NULL COMMENT 'Доходность к погашению эффективная (от индик. цены), в долях ',
  `offer_profit_effect` DECIMAL(16,10) DEFAULT NULL COMMENT 'Доходность к оферте эффективная (от индик. цены), в долях ',
  `coupon_profit_effect` DECIMAL(16,10) DEFAULT NULL COMMENT '??????',
  `clearance_profit_nominal` DECIMAL(16,10) DEFAULT NULL COMMENT 'Доходность к погашению номинальная (от индик. цены), в долях ',
  `offer_profit_nominal` DECIMAL(16,10) DEFAULT NULL COMMENT 'Доходность к оферте номинальная (от индик. цены), в долях ',
  `ytm_bid` DECIMAL(16,10) DEFAULT NULL COMMENT 'Доходность к погашению эфф. по цене Bid, в долях',
  `ytm_offer` DECIMAL(16,10) DEFAULT NULL COMMENT 'Доходность к погашению эфф. по цене Ask, в долях',
  `yto_bid` DECIMAL(16,10) DEFAULT NULL COMMENT 'Доходность к оферте эфф. по цене Bid, в долях',
  `yto_offer` DECIMAL(16,10) DEFAULT NULL COMMENT 'Доходность к оферте эфф. по цене Ask, в долях',
  `ytc_bid` DECIMAL(16,10) DEFAULT NULL COMMENT 'Текущая доходность по цене Bid, в долях',
  `ytc_offer` DECIMAL(16,10) DEFAULT NULL COMMENT 'Текущая доходность по цене Ask, в долях',
  `ytm_last` DECIMAL(16,10) DEFAULT NULL COMMENT 'Доходность к погашению эфф. по цене Last, в долях',
  `yto_last` DECIMAL(16,10) DEFAULT NULL COMMENT 'Доходность к оферте эфф. по цене Last, в долях',
  `ytc_last` DECIMAL(16,10) DEFAULT NULL COMMENT 'Текущая доходность по цене Last, в долях',
  `ytm_close` DECIMAL(16,10) DEFAULT NULL COMMENT 'Доходность к погашению эфф. по цене Close, в долях',
  `yto_close` DECIMAL(16,10) DEFAULT NULL COMMENT 'Доходность к оферте эфф. по цене Close, в долях',
  `ytc_close` DECIMAL(16,10) DEFAULT NULL COMMENT 'Текущая доходность по цене Close, в долях',
  `current_yield` DECIMAL(16,10) DEFAULT NULL COMMENT 'Текущая доходность, в долях',
  `indicative_yield` DECIMAL(16,10) GENERATED ALWAYS AS ((case when (`clearance_profit_effect` <> 0) then `clearance_profit_effect` when (`offer_profit_effect` <> 0) then `offer_profit_effect` when (`coupon_profit_effect` <> 0) then `coupon_profit_effect` else 0 end)) STORED COMMENT 'Индикативная доходность, в долях',
  `indicative_yield_type` VARCHAR(16) GENERATED ALWAYS AS ((case when (`clearance_profit_effect` <> 0) then _utf8mb4'Clearance' when (`offer_profit_effect` <> 0) then _utf8mb4'Offer' when (`coupon_profit_effect` <> 0) then _utf8mb4'Coupon' else NULL end)) STORED COMMENT 'Тип индикативной доходности',
  PRIMARY KEY (`id`)
  /* keys */
) /*!50100 TABLESPACE `innodb_file_per_table` */ ENGINE=InnoDB DEFAULT CHARSET=utf8mb4
/*!50100 PARTITION BY RANGE (`id`)
(PARTITION p1 VALUES LESS THAN     (400000000000000) DATA DIRECTORY = '/mysql_tablespaces/sd1t/tsq' ENGINE = InnoDB,
 PARTITION p4 VALUES LESS THAN     (500000000000000) DATA DIRECTORY = '/mysql_tablespaces/sd1t/tsq' ENGINE = InnoDB,
 PARTITION p7 VALUES LESS THAN     (800000000000000) DATA DIRECTORY = '/mysql_tablespaces/sd1t/tsq' ENGINE = InnoDB,
 PARTITION p19 VALUES LESS THAN   (2000000000000000) DATA DIRECTORY = '/mysql_tablespaces/sd1t/tsq' ENGINE = InnoDB,
 PARTITION p20 VALUES LESS THAN   (2100000000000000) DATA DIRECTORY = '/mysql_tablespaces/sd1t/tsq' ENGINE = InnoDB,
 PARTITION p70 VALUES LESS THAN   (7100000000000000) DATA DIRECTORY = '/mysql_tablespaces/sd1t/tsq' ENGINE = InnoDB,
 PARTITION p71 VALUES LESS THAN   (7200000000000000) DATA DIRECTORY = '/mysql_tablespaces/sd1t/tsq' ENGINE = InnoDB,
 PARTITION p90 VALUES LESS THAN   (9100000000000000) DATA DIRECTORY = '/mysql_tablespaces/sd1t/tsq' ENGINE = InnoDB,
 PARTITION p91 VALUES LESS THAN   (9200000000000000) DATA DIRECTORY = '/mysql_tablespaces/sd1t/tsq' ENGINE = InnoDB,
 PARTITION p109 VALUES LESS THAN (11000000000000000) DATA DIRECTORY = '/mysql_tablespaces/sd1t/tsq' ENGINE = InnoDB,
 PARTITION p119 VALUES LESS THAN (12000000000000000) DATA DIRECTORY = '/mysql_tablespaces/sd1t/tsq' ENGINE = InnoDB,
 PARTITION p149 VALUES LESS THAN (15000000000000000) DATA DIRECTORY = '/mysql_tablespaces/sd1t/tsq' ENGINE = InnoDB,
 PARTITION p167 VALUES LESS THAN (16800000000000000) DATA DIRECTORY = '/mysql_tablespaces/sd1t/tsq' ENGINE = InnoDB,
 PARTITION p236 VALUES LESS THAN (23700000000000000) DATA DIRECTORY = '/mysql_tablespaces/sd1t/tsq' ENGINE = InnoDB,
 PARTITION p240 VALUES LESS THAN (24100000000000000) DATA DIRECTORY = '/mysql_tablespaces/sd1t/tsq' ENGINE = InnoDB,
 PARTITION p244 VALUES LESS THAN (24500000000000000) DATA DIRECTORY = '/mysql_tablespaces/sd1t/tsq' ENGINE = InnoDB,
 PARTITION p254 VALUES LESS THAN (25500000000000000) DATA DIRECTORY = '/mysql_tablespaces/sd1t/tsq' ENGINE = InnoDB,
 PARTITION p255 VALUES LESS THAN (25600000000000000) DATA DIRECTORY = '/mysql_tablespaces/sd1t/tsq' ENGINE = InnoDB,
 PARTITION p258 VALUES LESS THAN (25900000000000000) DATA DIRECTORY = '/mysql_tablespaces/sd1t/tsq' ENGINE = InnoDB,
 PARTITION p300 VALUES LESS THAN (30100000000000000) DATA DIRECTORY = '/mysql_tablespaces/sd1t/tsq' ENGINE = InnoDB,
 PARTITION p333 VALUES LESS THAN (33400000000000000) DATA DIRECTORY = '/mysql_tablespaces/sd1t/tsq' ENGINE = InnoDB,
 PARTITION p414 VALUES LESS THAN (41500000000000000) DATA DIRECTORY = '/mysql_tablespaces/sd1t/tsq' ENGINE = InnoDB,
 PARTITION p499 VALUES LESS THAN (50000000000000000) DATA DIRECTORY = '/mysql_tablespaces/sd1t/tsq' ENGINE = InnoDB,
 PARTITION p0 VALUES LESS THAN MAXVALUE DATA DIRECTORY = '/mysql_tablespaces/sd1t/tsq' ENGINE = InnoDB) */