/* SHOW CREATE TABLE tsquotation.`40days_4ycurves`; */

CREATE TABLE tsquotation.`40days_4ycurves` (
 `id` bigint(20) unsigned NOT NULL COMMENT 'id результата торгов',
 `date` date NOT NULL DEFAULT '1900-01-01' COMMENT 'дата торгов',
 `place_id` int(11) NOT NULL DEFAULT '0' COMMENT 'id биржи',
 `emission_id` int(11) NOT NULL DEFAULT '0' COMMENT 'id Эмиссии (emission.id) - по которой торги',
 `emission_kind_id` int(11) NOT NULL DEFAULT '0',
 `emission_currency_id` int(11) NOT NULL DEFAULT '0',
 `emission_floating_rate` tinyint(1) NOT NULL DEFAULT '0',
 `emitent_id` int(11) NOT NULL DEFAULT '0',
 `emitent_country_id` int(11) NOT NULL DEFAULT '0',
 `emitent_type_value` int(11) NOT NULL DEFAULT '0',
 `emitent_branch_id` int(11) NOT NULL DEFAULT '0',
 `emitent_rating_scale2_point_id` int(11) NOT NULL DEFAULT '0' COMMENT 'Рейтинг эмитента от SnP, шкала id 2',
 `emitent_rating_scale6_point_id` int(11) NOT NULL DEFAULT '0' COMMENT 'Рейтинг эмитента от Fitch, шкала id 6',
 `emitent_rating_scale10_point_id` int(11) NOT NULL DEFAULT '0' COMMENT 'Рейтинг эмитента от Moody-s, шкала id 10',
 `lombard` tinyint(1) NOT NULL DEFAULT '0',
 `nkd` double DEFAULT NULL,
 `buying_quote` double DEFAULT NULL,
 `selling_quote` double DEFAULT NULL,
 `avar_price` double DEFAULT NULL,
 `clearance_profit_effect` double DEFAULT NULL,
 `offer_profit_effect` double DEFAULT NULL,
 `dur` double DEFAULT NULL,
 `dur_to` double DEFAULT NULL,
 `dur_mod` double DEFAULT NULL,
 `dur_mod_to` double DEFAULT NULL,
 `marketprice` double DEFAULT NULL,
 `admittedquote` double DEFAULT NULL,
 `legalcloseprice` double DEFAULT NULL,
 `mid_price` double DEFAULT NULL,
 `last_price` double DEFAULT NULL,
 `g_spread` double DEFAULT NULL,
 `t_spread` double DEFAULT NULL,
 `indicative_price` double DEFAULT NULL,
 `indicative_price_type` varchar(8) DEFAULT NULL,
 `indicative_yield` double DEFAULT NULL COMMENT 'Индикативная доходность',
 `indicative_yield_type` varchar(16) DEFAULT NULL COMMENT 'Тип индикативной доходности',
 `bid_ask_spread` double DEFAULT NULL COMMENT 'Спред bid ask',
 `duration` double DEFAULT NULL,
 `modified_duration` double DEFAULT NULL,
 `update_time` timestamp NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT 'Время последнего обновления записи',
 PRIMARY KEY (`id`,`place_id`,`date`,`emission_id`),
 UNIQUE KEY `pde` (`place_id`,`date`,`emission_id`),
 KEY `crrdp` (`emission_currency_id`,`date`,`place_id`),
 KEY `crrdc` (`emission_currency_id`,`date`,`emitent_country_id`),
 KEY `crrpd` (`emission_currency_id`,`place_id`,`date`),
 KEY `update_time` (`update_time`),
 KEY `du` (`date`,`update_time`),
 KEY `pdu` (`place_id`,`date`,`update_time`),
 KEY `ed` (`emission_id`,`date`),
 KEY `crrdl` (`emission_currency_id`,`date`,`lombard`),
 KEY `crrdfr` (`emission_currency_id`,`date`,`emission_floating_rate`) USING BTREE,
 KEY `dp` (`date`,`place_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='Котировки ТС, срез за 40 дней, InnoDB, партиции по place_id'
/*!50100 PARTITION BY RANGE (`place_id`)
(PARTITION p1 VALUES LESS THAN (2) ENGINE = InnoDB,
PARTITION p4 VALUES LESS THAN (5) ENGINE = InnoDB,
PARTITION p6 VALUES LESS THAN (7) ENGINE = InnoDB,
PARTITION p9 VALUES LESS THAN (10) ENGINE = InnoDB,
PARTITION p10 VALUES LESS THAN (11) ENGINE = InnoDB,
PARTITION p20 VALUES LESS THAN (21) ENGINE = InnoDB,
PARTITION p25 VALUES LESS THAN (26) ENGINE = InnoDB,
PARTITION p28 VALUES LESS THAN (29) ENGINE = InnoDB,
PARTITION p29 VALUES LESS THAN (30) ENGINE = InnoDB,
PARTITION p51 VALUES LESS THAN (52) ENGINE = InnoDB,
PARTITION p69 VALUES LESS THAN (70) ENGINE = InnoDB,
PARTITION p71 VALUES LESS THAN (72) ENGINE = InnoDB,
PARTITION p87 VALUES LESS THAN (88) ENGINE = InnoDB,
PARTITION p109 VALUES LESS THAN (110) ENGINE = InnoDB,
PARTITION p119 VALUES LESS THAN (120) ENGINE = InnoDB,
PARTITION p145 VALUES LESS THAN (146) ENGINE = InnoDB,
PARTITION p149 VALUES LESS THAN (150) ENGINE = InnoDB,
PARTITION p0 VALUES LESS THAN MAXVALUE ENGINE = InnoDB) */;